# Generated by Django 4.1.3 on 2022-12-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('latlan', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
