# Generated by Django 4.1.3 on 2022-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_markers_difficulty_markers_effect'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='bike',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markers',
            name='car',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
