# Generated by Django 4.1.3 on 2022-12-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_markers_delete_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='difficulty',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markers',
            name='effect',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
