# Generated by Django 4.1.3 on 2022-12-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_markers_bike_markers_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='bike',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='markers',
            name='car',
            field=models.CharField(max_length=255),
        ),
    ]
